default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: wanderlust
  password: password
  host: localhost

development:
  <<: *default
  database: wanderlust_development

test:
  <<: *default
  database: wanderlust_test

production:
  <<: *default
